### PR TITLE
CRW-297 parameterize all the things; rename...

### PR DESCRIPTION
**Pull request by nickboldt**
CRW-297 parameterize all the things; rename --organization to --crw-prefix; remove shortform variables for registries; fix sample path for docker --config and --from-file=.dockerconfigjson=

Change-Id: Icd9b15ed5ef0eb1acd9bf0e83db3e1224ea732bd
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
Please, don't forget, that it's aimed to be merged into release branch, that is 6.19.x.

**Comment by nickboldt** [comment]
Yes, I know. But also at master.

**Comment by dmytro-ndp** [comment]
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/pre-release/view/OCP%203.11/job/pre-release-upgrading-crw-1.1-to-1.2-on-OCP-using-migrate-script/25/consoleFull
```
Back-off pulling image "registry.redhat.io/redhat-identity-provider-7/identity-provider73-openshift:1.0-11"
```

**Comment by nickboldt** [comment]
Yeah. already fixed.

**Pull request merged**
