### PR TITLE
update to latest: node:8.15.1-alpine, ts...

### PR DESCRIPTION
**Pull request by nickboldt**
update to latest: node:8.15.1-alpine, ts 3.4.3, ts ls 0.3.7

Change-Id: Ic8d71ac55228ec358be8735af55a0dc640ce2aac
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Note that if we make this change we should probably also update the NODEJS_IMAGE_VERSION for the golang deps too as they use the same image.

**Comment by dmytro-ndp** [comment]
@nboldt: could you, please, explain, how that changes could be applied to stack images?

**Comment by nickboldt** [comment]
1. build this project. 
2. use the resulting tarball when building the container image from http://pkgs.devel.redhat.com/cgit/containers/codeready-workspaces-stacks-node/tree/Dockerfile?h=codeready-1.0-rhel-7#n63
3. build container locally, and then pull it into CRW as you would any custom stack image.... clone the node8 one, edit it to pull from a different container registry/name:tag, and launch the stack to see how it behaves.

**Comment by nickboldt** [comment]
9.19.x is dead.

**Pull request closed without merging**
